import Head from "next/head";
import NftCard from "./components/nft-card";
export default function Home() {
  return (
    <div>
      <Head>
        <title>NFT Card component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-very-dark-blue-main flex justify-center h-screen">
        <NftCard />
      </main>
      <footer></footer>
    </div>
  );
}
